remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: |
  League of Legends: What Roles Drive Team Success?
description: "This is a homework assignment for EECS 398 at the University of Michigan.<br>Author: Meghna Mahesh (meghnam@umich.edu)"
